on:
  workflow_call:
    inputs:
      checkout-ref:
        type: string
        default: ""
      upgrade-branch-title:
        type: string
        default: upgrade rust dependencies
      upgrade-branch-name:
        type: string
        default: update-msrv
      working-directory:
        type: string
        default: "."

jobs:
  cargo-msrv-upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.checkout-ref }}
          
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - uses: taiki-e/install-action@542cebaaed782771e619bd5609d97659d109c492 # v2.66.7
        with:
          tool: cargo-msrv

      - run: |
          cat Cargo.toml | sed -z 's/rust-version.*\n//mg' > Cargo2.toml
          mv Cargo2.toml Cargo.toml
          
      - run: cargo msrv find --ignore-lockfile --write-msrv
      
      - run: echo "message=update msrv @ $(date +%Y%m%dT%H:%M:%S%Z)" >> "$GITHUB_ENV"
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          commit-message: ${{ env.message }}
          title: ${{ inputs.upgrade-branch-title }}
          branch: ${{ inputs.upgrade-branch-name }}
