on:
  workflow_call:
    inputs:
      checkout-ref:
        type: string
        default: ""
      upgrade-branch-title:
        type: string
        default: upgrade rust dependencies
      upgrade-branch-name:
        type: string
        default: update-msrv
      working-directory:
        type: string
        default: "."

jobs:
  cargo-msrv-upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ inputs.checkout-ref }}
          
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - uses: taiki-e/install-action@3575e532701a5fc614b0c842e4119af4cc5fd16d # v2.62.60
        with:
          tool: cargo-msrv

      - run: |
          cat Cargo.toml | sed -z 's/rust-version.*\n//mg' > Cargo2.toml
          mv Cargo2.toml Cargo.toml
          
      - run: cargo msrv find --ignore-lockfile --write-msrv
      
      - run: echo "message=update msrv @ $(date +%Y%m%dT%H:%M:%S%Z)" >> "$GITHUB_ENV"
      - uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          commit-message: ${{ env.message }}
          title: ${{ inputs.upgrade-branch-title }}
          branch: ${{ inputs.upgrade-branch-name }}
