on:
  workflow_call:
    inputs:
      checkout-ref:
        type: string
        default: ""
      upgrade-branch-title:
        type: string
        default: upgrade rust dependencies
      upgrade-branch-name:
        type: string
        default: update-msrv
      working-directory:
        type: string
        default: "."

jobs:
  cargo-msrv-upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ inputs.checkout-ref }}
          
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2
      - uses: taiki-e/install-action@6cc14f7f2f4b3129aff07a8b071d2d4f2733465d # v2
        with:
          tool: cargo-msrv

      - run: |
          cat Cargo.toml | sed -z 's/rust-version.*\n//mg' > Cargo2.toml
          mv Cargo2.toml Cargo.toml
          
      - run: cargo msrv find --ignore-lockfile --write-msrv
      
      - run: echo "message=upgrade rust dependencies @ $(date +%Y%m%dT%H:%M:%S%Z)" >> "$GITHUB_ENV"
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: ${{ env.message }}
          title: ${{ inputs.upgrade-branch-title }}
          branch: ${{ inputs.upgrade-branch-name }}
