on:
  workflow_call:
    inputs:
      checkout-ref:
        type: string
        default: ""
      upgrade-branch-title:
        type: string
        default: upgrade rust dependencies
      upgrade-branch-name:
        type: string
        default: update-msrv
      working-directory:
        type: string
        default: "."

jobs:
  cargo-msrv-upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.checkout-ref }}
          
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-msrv

      - run: |
          cat Cargo.toml | sed -z 's/rust-version.*\n//mg' > Cargo2.toml
          mv Cargo2.toml Cargo.toml
          
      - run: cargo msrv find --ignore-lockfile --write-msrv
      
      - run: echo "message=upgrade rust dependencies @ $(date +%Y%m%dT%H:%M:%S%Z)" >> "$GITHUB_ENV"
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: ${{ env.message }}
          title: ${{ inputs.upgrade-branch-title }}
          branch: ${{ inputs.upgrade-branch-name }}
